name: Custom Build

on:
  push:
    branches:
      - custom-build
  workflow_dispatch:

concurrency:
  group: custom-build
  cancel-in-progress: true

jobs:
  amd64_tensorrt:
    runs-on: ubuntu-22.04
    name: Custom TensorRT (x86 GPU)
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up QEMU and Buildx
        id: setup
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push TensorRT (x86 GPU)
        env:
          COMPUTE_LEVEL: "50 60 70 80 90"
        uses: docker/bake-action@v6
        with:
          source: .
          push: true
          targets: tensorrt
          files: docker/tensorrt/trt.hcl
          set: |
            tensorrt.tags=ghcr.io/${{ github.repository }}:custom-tensorrt
            *.cache-from=type=registry,ref=ghcr.io/${{ github.repository }}:cache-custom-tensorrt
            *.cache-to=type=registry,ref=ghcr.io/${{ github.repository }}:cache-custom-tensorrt,mode=max
